/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.fortune;

import static org.junit.Assert.assertNotNull;
import org.junit.Test;

public class AppTest {
  @Test public void testAppHasAGreeting() {
    ClientApp classUnderTest = new ClientAppApp();
    assertNotNull("app should have a greeting", classUnderTest.getGreeting());
  }
}
